server:
  port: 8888
demo:
  region: me-dubai-1
  tenancyId: ocid1.tenancy.oc1..assssssssssssssssssssssssscb47hra26p4q
  userId: ocid1.user.oc1..aaaaaaaafawx54qccccxxcxcxcxcxcxcxcxnds5tcsd5vlvfl3via
  fingerprint: 36:7e:fa:9a:4f:a2:3f:db:7b
  keypath: /home/opc/.oci/oci_api_key.pem
  vaultId: ocid1.vault.oc1.me-dubai-1.ejrhxdddsdssdewewewewecb4dobfcpxilb6caxxginqd5mni3qfaopwnra
  masterKeyId: ocid1.key.oc1.me-dubai-1.ejrhzhs5aafgg.abshxsfwfwerwgsafsdfxhgwao45kpbkznckcb6agu77cthsfcq
  compartmentId: ocid1.compartment.oc1..aaaaaaaacmdop4fwrdafasdfaewrwggwefwea4lo7ittea5wdq
